INSERT INTO GENRES (NAME)
    VALUES ('Комедия');
INSERT INTO GENRES (NAME)
    VALUES ('Драма');
INSERT INTO GENRES (NAME)
    VALUES ('Мультфильм');
INSERT INTO GENRES (NAME)
    VALUES ('Триллер');
INSERT INTO GENRES (NAME)
    VALUES ('Документальный');
INSERT INTO GENRES (NAME)
    VALUES ('Боевик');

INSERT INTO RATING_MPA (NAME)
    VALUES ('G');
INSERT INTO RATING_MPA (NAME)
    VALUES ('PG');
INSERT INTO RATING_MPA (NAME)
    VALUES ('PG-13');
INSERT INTO RATING_MPA (NAME)
    VALUES ('R');
INSERT INTO RATING_MPA (NAME)
    VALUES ('NC-17');

INSERT INTO FRIEND_STATUS (NAME)
    VALUES ('CONFIRMED');
INSERT INTO FRIEND_STATUS (NAME)
    VALUES ('UNCONFIRMED');